### ISSUE TITLE
New Minigame

### ISSUE THREAD

**Issue by BlueGhostAlt** [snollygolly/sourceio-automation#7] opened 2017-06-30 18:11 UTC
An update happened to the game and now the hack doesn't work anymore

**Comment by bozoweed** [comment] 2017-07-01 03:10
my bot is working come take in my github

**Comment by snollygolly** [comment] 2017-07-01 03:24
I'll take a look at it.

**Comment by snollygolly** [comment] 2017-07-01 03:26
Can you be more specific @TheSourceCod3Coder ?

I just loaded up the script and the newest version of the game and it works fine for me.

**Comment by bozoweed** [comment] 2017-07-01 03:55
you can delete me snollygolly but you can't delete your bug ^^ and for you know , he got my link on mail so delete here is not delete on is mail ;) NO RAGE just leak

**Comment by bozoweed** [comment] 2017-07-01 03:57
this is my link https://github.com/bozoweed/Bot-s0urce.io

**Comment by snollygolly** [comment] 2017-07-06 13:22
Can't reproduce, closing.  Please re-open if you have more information.

**Closed as completed by snollygolly** 2017-07-06 13:22 UTC
