### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by freaky767** [snollygolly/sourceio-automation#10] opened 2017-07-06 22:03 UTC
Whenever you are hacking somebody, and then the port closes, the bot just stays still, and does nothing, until you restart the bot, or you start hacking somebody.
Any fix?

**Comment by snollygolly** [comment] 2017-07-07 13:21
Duplicate of #11. closing.

**Closed as completed by snollygolly** 2017-07-07 13:21 UTC

**Comment by freaky767** [comment] 2017-07-07 14:29
but i opened this issue a lot earlier?

**Comment by snollygolly** [comment] 2017-07-07 15:56
Doesn't matter, both are consolidated into one now.  It's the same root cause as well, one fix will fix them both.
